# Generated by Django 4.2.24 on 2025-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID задачи Celery')),
                ('channel_username', models.CharField(max_length=100)),
                ('days_to_analyze', models.IntegerField(default=30)),
                ('price', models.FloatField(default=1000.0)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('PROGRESS', 'В процессе'), ('SUCCESS', 'Успешно'), ('FAILURE', 'Ошибка')], default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат анализа')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
